reg_util = @(k,klabels,addlargs) optk_scaled_2019(k,klabels,addlargs{:});
fga = @(k) reg_util(k,klabelsdef,addlargs);
fdebug = @(k) reg_util(k,klabelsdef,{addlargs{:},'plot_sol',true,...
  'save_for_debug',true,'eval_stats',true});
fdebugvarg = @(k,varargin) reg_util(k,klabelsdef,{addlargs{:},...
  'plot_sol',true,'save_for_debug',true,'eval_stats',true,varargin{:}});
param_sweep_args = {addlargs{:},'plot_sol',true,...
  'save_for_debug',true,'eval_stats',true};